// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_about_the_sea = "CgkI8L7s1aoOEAIQAg"; // <GPGSID>
        public const string achievement_wow_amazing = "CgkI8L7s1aoOEAIQCA"; // <GPGSID>
        public const string achievement_getting_started = "CgkI8L7s1aoOEAIQBQ"; // <GPGSID>
        public const string leaderboard_scoreboard = "CgkI8L7s1aoOEAIQAQ"; // <GPGSID>
        public const string achievement_professional = "CgkI8L7s1aoOEAIQBw"; // <GPGSID>
        public const string achievement_taking_off = "CgkI8L7s1aoOEAIQBg"; // <GPGSID>
        public const string achievement_in_the_clouds = "CgkI8L7s1aoOEAIQBA"; // <GPGSID>
        public const string achievement_land_in_sight = "CgkI8L7s1aoOEAIQAw"; // <GPGSID>

}

